# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variables
ENV MQTT_BROKER_HOST localhost
ENV MQTT_BROKER_PORT 1883
ENV REDIS_HOST localhost
ENV REDIS_PORT 6379

# Command to run the subscriber_redis.py script
CMD ["python", "subscriber_redis.py"]

